#!/bin/bash
# -*- mode: sh -*-


REPOS=$(cat .repos)

for repo in $REPOS; do
    echo "-- $repo --"
    if [ -d $repo ]; then
        git -C $repo "$@"
    else
        echo "  $repo is not available"
    fi
done | less
